
[package]
name = "unpfs"
version = "0.0.1"
authors = [ "afpacket <afpacket@gmail.com>" ]

[[bin]]
name = "unpfs"

[dependencies]
nix = "0.7"
env_logger = "0.3"
filetime = "0.1"

[dependencies.rust-9p]
path = "../../"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
